### ISSUE TITLE
@mention does not work the way it should

### ISSUE THREAD

**Issue by MrMooky** [XetaIO/Xetaravel-Mentions#10]
When I start a conversation with `@username`, the name is not linked correctly. But when I write something like `Hej @username` the name gets linked correctly.

**Comment by ow** [comment]
Hey! The repository seems inactive but I submitted a PR that addresses this for my environment: https://github.com/XetaIO/Xetaravel-Mentions/pull/12

**Comment by Xety** [comment]
@MrMooky You can modifiy the regex, check the readme.
