### ISSUE TITLE
Package not installing in Laravel 5.7

### ISSUE THREAD

**Issue by Husnaindev505** [XetaIO/Xetaravel-Mentions#14]
Problem 1
    - xetaio/xetaravel-mentions v2.0.0 requires laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev].
    - xetaio/xetaravel-mentions v2.0.1 requires laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev].
    - Conclusion: don't install laravel/framework 5.6.x-dev
    - Installation request for xetaio/xetaravel-mentions ^2.0 -> satisfiable by xetaio/xetaravel-mentions[v2.0.0, v2.0.1].

**Comment by Xety** [comment]
Try again please
