### ISSUE TITLE
Not a bug report: Character config for html string

### ISSUE THREAD

**Issue by ArtMin96** [XetaIO/Xetaravel-Mentions#27]
I use [trix editor](https://github.com/basecamp/trix). From the Trix editor, username comes as an html string eg. `<p>@mentionable</p>`. What value should I give to character config?

**Comment by Xety** [comment]
It should still work the same way as without HTML tag.
You can also customize the regex if needed : https://github.com/XetaIO/Xetaravel-Mentions#parser-configuration
