### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by kiritokatklian** [XetaIO/Xetaravel-Mentions#29]
@Xety Hey! Thanks for your work on this package 👍
Is it possible to update it to work with Laravel 10?

**Comment by kiritokatklian** [comment]
@Xety I quickly updated the composer config to add Laravel 10 support #30. There were no issues when I ran the tests locally, but please make sure it works as intended before merging 😄

**Comment by Xety** [comment]
Hello,
Support for Laravel 10 has been added in #31 a new release has been drafted too.
