### ISSUE TITLE
Getting QueryException

### ISSUE THREAD

**Issue by MrMooky** [XetaIO/Xetaravel-Mentions#9]
Laravel 5.6.38
PHP 7.1

I'm getting this message when mentioning another user: 

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `mentions` (`model_type`, `model_id`, `recipient_type`, `recipient_id`, `updated_at`, `created_at`) values (App\Timeline, , App\User, 2, 2018-09-16 10:51:35, 2018-09-16 10:51:35))
```

I set up the Notifications as described in the Laravel docs as well as in your docs. What could cause this problem?

**Comment by Xety** [comment]
#8 I think this PR should fix this problem.

**Comment by MrMooky** [comment]
Still getting this error:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `mentions` (`model_type`, `model_id`, `recipient_type`, `recipient_id`, `updated_at`, `created_at`) values (App\Timeline, , App\User, 25, 2019-02-03 16:20:45, 2019-02-03 16:20:45))
```

**Comment by Xety** [comment]
That's because the field `model_id` can't be null.
What's your `Timeline` model used for ? Do you have a table for this model ?

**Comment by MrMooky** [comment]
I understand the problem about the `model_id` field being null.

The `Timeline` model is used for a timeline, where users post messages – like a pinboard and it has a table with the following fields:

id `int`
user_id `int`
allow_comments `int`
text `text`
image `varchar`
created_at `timestamp`
updated_at `timestamp`

I checked the **app/Notifications/MentionNotification.php** function `toDatabase` but was not sure where exactly the fields are defined. I even tried setting the `model_id` manually, but still got the `null` error.

Definied is `App\User::class` as model in config/mentions.php, which is correct. But I need to mention a user when submitting a post, currently looks like this:

```
$post = new Timeline;
$parser = new MentionParser($post, [
    'regex' => '/({character}{pattern}{rules})/',
    'regex_replacement' => [
        '{character}' => '@',
        '{pattern}' => '[A-Za-z0-9]',
        '{rules}' => '{1,20}'
    ]
]);
$parser->setOption('mention', true);
$post->text = $parser->parse($request->posttext);
...
$post->save();
```

**Comment by Xety** [comment]
With `$post = new Timeline;` do you have the `id` of the new `Timeline` in the `$post` ? If not, try with `Timeline::create()` https://laravel.com/docs/5.7/eloquent#mass-assignment 
Also you need to add the `HasMentionsTrait` to the Timeline model :
```php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Xetaio\Mentions\Models\Traits\HasMentionsTrait;

class Timeline extends Model
{
    use HasMentionsTrait;
}
```

The mentions are saved there : https://github.com/XetaIO/Xetaravel-Mentions/blob/master/src/Models/Repositories/MentionRepository.php#L31 try to debug it to see what `$model` containt.

**Comment by MrMooky** [comment]
`Timeline::create()` did it, thanks.

**Comment by Xety** [comment]
Yeah i think `new Timeline` don't return the id since it's not saved in the database yet, taht's why you got the `model_id` field being null.
